### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by dherl0623** [mykle1/MMM-JEOPARDY#1]
I love this module as my wife and I enjoy Jeopardy! I wondered if there was any way you could add a countdown timer to when the answer is going to show? Maybe where the answer will be showing up have some sort of faded timer counting down. I'm not overly good at Javascript myself, but I may try screwing around with it if I get time. Otherwise, this is a great and fun module! Thanks!

**Comment by dherl0623** [comment]
Thinking that I may be able to reverse engineer this repo: https://github.com/fewieden/MMM-VocabularyTrainer

**Comment by mykle1** [comment]
Hi, I'm glad you and your wife are enjoying the module. My family watches Jeopardy every night and we make a fun, competitive, family thing out of it. Great fun. I can't make any promises regarding your request but I will take a look at it as time allows. If you make modifications of your own I'd be happy to merge them into the repo. :-)
